### ISSUE TITLE
[Feature] Refactor random operations

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#14]
This is a matter of opinion, but I would like to refactor and simplify random write and random read.
The way it works now is computing target number of IOs (based on max_random_reads or max_random _writes) and computing segment size (which is almost always 2 times random record size).
The target number of IOs is the number of random offset seeks that will happen and at any of those, computed segment size will be written/read.
This is very confusing and doesn't meet expectations of an actual random IO, f.e. if I want to measure random IO with a given record size, I will actually get performance of two blocks issued in sequence.

In my usage, instead of computing segment size and parametrising max random requests, I just get some random size that I want to randomly read/write and do a new random_seek_offset before issuing a new record, i.e. the process similar to os_append or read, but setting random offset before every IO. This would simplify the code for these operations and would make it more straightforward and easy to use.

**Comment by bengland2** [comment]
yeah I guess this is confusing, I had intended to make the I/O pattern be a mix of sequential and random which I had seen in some applications.   But I think we can get pretty much the same effect by having a mix of I/O sizes, with a few large I/Os mixed in with smaller I/Os.
