### ISSUE TITLE
[Feature] Better controlled record size

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#20]
Sometimes, I want to work with fixed record size (block size) and sometimes I want the random record size to be of a defined range.
Setting only a max value (max-record-size) is pretty limiting in this regard.
I propose to include parameter for setting either fixed record size, e.g.:

--record-size 8k

and adjustable range, e.g.:
--record-size 8k:64k

The original functionality could be invoked by setting the lower bound to 1b

**Comment by spetrovi** [comment]
Deprecating max_record_size_kb, but keeping the arg so it doesn't break anyone's tests. 
However, any input to max_record_size_kb will be overwritten by --record_size setting

**Comment by spetrovi** [comment]
Good perk of this is that we can reuse the functionality for better control of file size.

**Comment by bengland2** [comment]
that's fine to have --record-size override max-record-size, as long as I get the option to use max-record-size still.      We could also have done a min-record size, and if min-record-size = max-record-size that would amount to the same thing as record-size, but this is fine

**Comment by spetrovi** [comment]
Well the original functionality of --max-record-size-kb could be achieved by specifying the range (with ":") and making the lower bound 1B.
Thus, the equivalent of --max-record-size-kb 64 would be --record-size 1:64K
Should we keep --max-record-size-kb nevertheless?

**Comment by spetrovi** [comment]
Ok, my solution: 
Let's keep --max-record-size-kb, but default will be None. However, if someone wants to use this parameter, it will override anything that's in --record-size with (1:value * BYTES_PER_KiB).
This means, any older configs will still work, but there's freedom to use advanced --record-size options normally.
