### ISSUE TITLE
[Feature] Accept different size units for file size

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#29]
I think for the fs-drift to feel more professional we should accept different unit sizes like kb, mb, gb, etc.
Nothing fancy and no differentiation between KiB and KB needed, just parse the input value, so we don't have to specify the unit in the parameter name.

**Comment by spetrovi** [comment]
Let's just treat file size the same way we do record size.

**Comment by bengland2** [comment]
can easily do this by creating a "data type" for file/record size and having this data type parse the suffix.   @spetrovi I disagree that no differentiation between KiB and KB needed.    KiB is a power of 2, KB is a power of 10.   [See this reference](https://www.techtarget.com/searchstorage/definition/mebibyte-MiB#:~:text=A%20mebibyte%20(MiB)%20is%20a,220%20or%201%2C048%2C576%20bytes.).   It matters for 2 reasons: a) alignment on page boundaries can only be achieved with KiB or MiB, and b) the difference between GB and GiB is significant, and larger units get more significant.

**Comment by bengland2** [comment]
Suggest we add a routine to [parser_data_types.py](https://github.com/parallel-fs-utils/fs-drift/blob/master/parser_data_types.py) to parse file/record sizes as you describe, and then call that from opts.py.   This module allows you to write parsing code once and re-use it in all cases where you need it in the CLI arg parser.

**Comment by spetrovi** [comment]
Well of course I perceive the differences between the two units ;) but from the original fs-drift code I got an impression that we don't care that much:
For example, value obtained by --max-file-size-kb or --max-record-size-kb is always converted using BYTES_PER_KiB.
Should we just mention the we use 1024 base in the README and call it a day? Or should we parse all possible units?
P.S. I will move the parsing method to parser_data_types,py, I don't know why I didn't do it right away.

**Comment by spetrovi** [comment]
Ok, I moved the parsing logic to parser_data_types.
I decided that we can continue with using only base 2 units, since I have no desire to test with SI units. However, I updated documentation to mention this to clear any confusion.

**Comment by spetrovi** [comment]
I ended up doing the same as with record size. If max-file-size-kb  is set, it overrides anything in file-size.
Otherwise, file-size accepts different base 2 units (b, k, m, g) and also accepts range (two values separated by ":").
