### ISSUE TITLE
[Bugfix] directIO without rawdevice throws exceptions

### ISSUE THREAD

**Issue by bengland2** [parallel-fs-utils/fs-drift#35]
It would be nice to have ability to use direct I/O without using a raw device as a way of testing filesystems.  When I run:

```
rm -rf /tmp/mydir 
mkdir /tmp/mydir 
./fs-drift.py --top /tmp/mydir  --duration 5 --response-times True --max-record-size-kb 4 --max-file-size-kb 1048576 --threads 8 --report-interval 1 --random-distribution gaussian --mean-velocity 10.0 --directIO True --output-json /tmp/fs-drift-result.json \
	2>&1 | tee broken.log
```

I get a lot of exceptions like this one being logged:

```
...
thrd.03 2022-02-24 08:46:19,352 - ERROR - [Errno 22] Invalid argument: './d0002/d0002/f000000109'
Traceback (most recent call last):
  File "/home/bengland/fs-drift/fsop.py", line 602, in op_random_write
    fd = os.open(fn, os.O_WRONLY | os.O_DIRECT * self.params.directIO)
OSError: [Errno 22] Invalid argument: './d0002/d0002/f000000109'
thrd.02 2022-02-24 08:46:19,352 - ERROR - [Errno 22] Invalid argument: './d0003/d0003/f000000178'
Traceback (most recent call last):
  File "/home/bengland/fs-drift/fsop.py", line 380, in op_read
    fd = os.open(fn, os.O_RDONLY | os.O_DIRECT * self.params.directIO)
...
```

At a minimum we should restrict directIO to raw devices until this issue is resolved.

**Comment by spetrovi** [comment]
Hi Ben, of course using directIO on files/filesystem is intended usage.
When I run these commands, I get none of the errors (master branch) and the fs-drift finishes normally.
I need to find a way to reproduce this bug, but so far, it seems to me it's not directIO related.

**Comment by bengland2** [comment]
so it turns out that the problem doesn't happen if you run as root.  But the error you get is strange, EINVAL

**Comment by spetrovi** [comment]
This is weird, I'm trying to obtain some minimal code to replicate this, but so far, no luck.

**Comment by spetrovi** [comment]
So, this is for sure a problem with permissions in the /tmp folder. If I create a directory in my account tree (e.g. /home/spetrovi/mydir), the fs-drift runs without errors.
We only get _OSError: [Errno 22] Invalid argument:_ when using other, non-user paths, like /tmp
Minimal code to reproduce the error:
`import os`
`fd = os.open('/tmp/testfile', os.O_CREAT | os.O_EXCL | os.O_WRONLY | os.O_DIRECT)`
Output after running this:
`[spetrovi@localhost fs-drift]$ python3 minimal.py `
`Traceback (most recent call last):`
`  File "/home/spetrovi/git/hubgit/fs-drift/minimal.py", line 5, in <module>`
`    fd = os.open('/tmp/testfile', os.O_CREAT | os.O_EXCL | os.O_WRONLY | os.O_DIRECT)`
`OSError: [Errno 22] Invalid argument: '/tmp/testfile'`

**Comment by spetrovi** [comment]
After some digging, I found out it's actually a problem with tmpfs, which doesn't support directIO opens, as per this email thread:
https://lore.kernel.org/lkml/459D290B.1040703@tmr.com/t/

So there's no real bugfix to be done. We can only avoid using directIO with /tmp. I'd change the regtest path from /tmp to /var/tmp, since that seems to work. We should also mention this in README to avoid future confusion.
