### ISSUE TITLE
[Feature] DirectIO

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#7]
Sometimes, I'm interested in performance of the stack/device/fs without Linux page-cache interfering and boosting the measured numbers.
This can be achieved by opening the target file (or device) with the O_DIRECT flag. However, to successfully administer IO using the O_DIRECT flag, the data have to be properly aligned.
One way I found out to do this is writing the data to an mmap object and use that to write to the actual file. For reads, we need to read the data to an mmap object.
This means slight increase in code complexity, but should have no effect on performance.

**Comment by spetrovi** [comment]
Question is, if the block alignment should be always present or only when this option is triggered.

**Comment by bengland2** [comment]
clearly, the data has to be properly aligned for O_DIRECT, so I would force block alignment in this case, just let the user know that you are doing that (log message).

**Comment by spetrovi** [comment]
Right!
