### ISSUE TITLE
[Feature] Discard operation

### ISSUE THREAD

**Issue by spetrovi** [parallel-fs-utils/fs-drift#8]
With more complex logical stacks, there is an increasing need of keeping performance of discard operation in check. FIO reacted to this need by adding trim and randtrim IOs to the list.
I was able to code in a random discard operation by invoking a specific ioctl. The code complexity doesn’t change, it’s just a new method in fsop.py. However, we should make it more robust, f.e. detecting if the user isn’t trying to run it on a device that doesn’t support discard etc. We should also make sure to mention in the documentation that this will only work for raw device option and can seriously damage file system.

**Comment by bengland2** [comment]
fs-drift should prevent trim on a filesystem, as this would be done with [fstrim](https://man7.org/linux/man-pages/man8/fstrim.8.html).  We know whether it's using a block device, so just throw an exception if trim is attempted with a block device.   The workload table in normalized_weights should not contain any trim operations in this case.
